### ISSUE TITLE
NodeBase query by entityId?

### ISSUE THREAD

**Issue by jansorg** [JetBrains/xodus-dnq#45]
Thanks for adding `entityId` / `xdId`!

Is there a way to create a `NodeBase` query to locate by `entityId`? This would be useful to have generic, user-defined queries.
I currently store xdId in a property of type String, but that's inefficient.

**Comment by lehvolk** [comment]
There is an extension method `XdEntityType.findById`.  You can wrap result into `XdQuery` and intersect it with result of query by other properties. 

At the moment such NodeBase is not implemented on the database level because there is a direct method to get `Entity` based on id.

>I currently store xdId in a property of type String, but that inefficient.

I don't get your point. Could you please elaborate.

**Comment by jansorg** [comment]
@lehvolk Thanks, I'll have a look at `findById`.
I meant that I currently have a property called `id` which stores the value of `xdId` and which I currently use in NodeBase queries. But I added `id` before `xdId` was there and duplicating `xdId` is inefficient.
