### ISSUE TITLE
Error when using XdEnumEntityType

### ISSUE THREAD

**Issue by aaistom** [JetBrains/xodus-dnq#64]
I've added the example from documentation and tried to build, but there is an error:
`
e: /<my_path>/app/build/tmp/kapt3/stubs/main/my/app/package/db/xodus/XdGender.java:31: error: as of release 5, 'enum' is a keyword, and may not be used as an identifier
    public static final class Companion extends kotlinx.dnq.enum.XdEnumEntityType<my.app.package.db.xodus.XdGender> {
`
As I understand XdEnumEntityType is located in **kotlinx.dnq.enum**, but we cannot use enum in java code. Please help me fix this issue.

**Comment by lehvolk** [comment]
@aaistom on the one hand there is no strong reason for storing this class in "enum" package. At the moment I found  no way to workaround this error for Java compiler. 

On the other hand it's worth to use xodus-dnq with Kotlin because library DSL extensively uses delegates and other Kotlin features which do not have Java analogues. Kotlin compiler handles this package perfectly fine.

So at the moment if your are trying to use it in Java code you can try to create a Kotlin class which extends XdEnumEntityType and use it as a parent for your Java classes.

**Comment by aaistom** [comment]
@lehvolk I added xodus dnq in my KOTLIN project. I investigated the problem: my project used kapt, so I have kaptGenerateStubsKotlin and kaptKotlin which is running sequentially. These tasks generated java code from kotlin classes and there is the problem with enum, so kaptKotlin task is failed.

**Comment by lehvolk** [comment]
I moved this class to the parent package since there is no reason for storing it into a dedicated package.
